 server:
  port: 1111
  
 
 spring:
  h2:
    console:
      path: /h2console
      enabled: true
  datasource:
    url: jdbc:h2:~/productmicroservice
    username: sa
    password: 
    driver-class-name: org.h2.Driver
 
  jpa:
    properties:
      hibernate:
      dbcp2:
      ddl-auto: update  
      show-sql: true  
      hibernate.generate_statistics: true 


   

  